config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
    
    member do
      post :follow
      post :unfollow
    end
    
    resources :reviews
  end
  
  namespace :account do
    resources :movies
  end
  
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews
  validates :title, presence: true
  
  has_many :movie_relationships
  has_many :followers, through: :movie_relationships, source: :user
end

app/models/movie_relationship.rb
class MovieRelationship < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  
  validates :content, presence: true
  
  scope :recent, -> { order("created_at DESC") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :movies
  has_many :reviews
  
  has_many :movie_relationships
  has_many :participated_movies, :through => :movie_relationships, :source => :movie
  
  def is_follower_of?(movie)
    participated_movies.include?(movie)
  end
  
  def follow!(movie)
    participated_movies << movie
  end
  
  def unfollow!(movie)
    participated_movies.delete(movie)
  end
end

app/controllers/account/movies_controller.rb
class Account::MoviesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @movies = current_user.participated_movies
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy, :follow, :unfollow]
  def index
    @movies = Movie.all
  end
  
  def show
    @movie = Movie.find(params[:id])
    @reviews = @movie.reviews.recent.paginate(:page => params[:page], :per_page => 5)
  end
  
  def edit
    @movie = Movie.find(params[:id])
  end
  
  def new
    @movie = Movie.new
  end
  
  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    
    if @movie.save
      current_user.follow!(@movie)
      redirect_to movies_path
    else
      render :new
    end
  end
  
  def update
    @movie = Movie.find(params[:id])
    
    if @movie.update(movie_params)
      redirect_to movies_path, notice: "Update Scuccess"
    else
      render :edit
    end
  end
  
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:alert] = "Movie deleted"
    redirect_to movies_path
  end
  
  def follow
    @movie = Movie.find(params[:id])
    
    if !current_user.is_follower_of?(@movie)
      current_user.follow!(@movie)
      flash[:notice] = "成功收藏本电影"
    else
      flash[:warning] = "你已经收藏了该电影"
    end
    
    redirect_to movie_path(@movie)
  end
  
  def unfollow
    @movie = Movie.find(params[:id])
    
    if current_user.is_follower_of?(@movie)
      current_user.unfollow!(@movie)
      flash[:alert] = "已经停止关注该电影"
    else
      flash[:waring] = "您原本就没有收藏该电影..."
    end
    
    redirect_to movie_path(@movie)
  end
  
  private
  def movie_params
    params.require(:movie).permit(:title, :theaterdate, :description)
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]
  before_action :find_movie_and_check, :only => [:new, :create]
  
  def new
    # @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end
  
  def create
    # @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.movie = @movie
    @review.user = current_user
    
    if @review.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end
  
  private
  
  def find_movie_and_check
    @movie = Movie.find(params[:movie_id])
    if !current_user.is_follower_of?(@movie)
      redirect_to movie_path(@movie), alert: "只有收藏了电影才能进行评论"
    end
  end
  
  def review_params
    params.require(:review).permit(:content)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
    flash[:warning] = "早安！你好！"
    flash[:alert] = "早安！你好！"
  end
end

app/helpers/account/movies_helper.rb
module Account::MoviesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze
  
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
	<% user_facing_flashes.each do |key, value| %>
		<div class="alert alert-dismissable alert-<%= flash_class(key) %>">
			<button class="close" data-dismiss="alert">x</button>
			<%= value %>
		</div>
	<% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
	<p class="text-center">Copyright @2016 电影评论网
		<br>Design by
		<a href="http://douban.com" target=_new>Douban</a>
	</p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a href="/" class="navbar-brand">电影评论网</a>
		</div>
		
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<% if !current_user %>
					<li><%= link_to("注册", new_user_registration_path) %></li>
					<li><%= link_to("登录", new_user_session_path)%></li>
				<% else %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Hi!, <%= current_user.email %>
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to("我的收藏", account_movies_path) %></li>
							<li class = "divider"></li>
							<li><%= link_to("退出", destroy_user_session_path, method: :delete) %></li>
						</ul>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieCommunity</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  
	  <div class="container-fluid">
	  	<%= render "common/navbar" %>
		<%= render "common/flashes"%>
		<%= yield %>
	  </div>
	  
	  <%= render "common/footer" %>
	  
  </body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f|%>
	<div class="form-group">
		<%= f.input :title, label: '电影名称', input_html: { class: "form-control" } %>
		<%= f.input :theaterdate, label: '上映日期', input_html: { class: "form-control"}%>
		<%= f.input :description, label: '简介', input_html: { class: "form-control" } %>
	</div>
	<%= f.submit "提交", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

<!-- <%= form_for @movie do |f| %>
<% if @movie.errors.any? %>
<ul>
	<% @movie.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
</ul>
<% end %>
电影名称：
<%= f.text_field :title %>
<br>
导演：
<br>
编剧：
<br>
主演：
<br>
上映日期：
<%= f.text_field :theaterdate %>
<br>
片长
<br>
剧情简介:
<br>
<%= f.text_area :description %>
<br>

<%= f.submit "提交", :disable_with => 'Submiting...' %>
<% end %> -->

app/views/movies/edit.html.erb
<div class="col-md-4 col-md-offset-4">
	<h2>编辑电影信息</h2>
	
	<hr>

	<%= render "form" %>
	
</div>

app/views/movies/index.html.erb
<div class="col-md-12">
	<div class="group">
		<% if current_user %>
			<%= link_to("创建电影", new_movie_path, class: "btn btn-primary pull-right") %>
		<% end %>
	</div>
	<table class="table table-hover">
		<thead>
			<tr class="text-center">
				<td>#</td>
				<td>电影名</td>
				<td>简介</td>
				<td>上映日期</td>
			</tr>
		</thead>
		<tbody>
			<% @movies.each do |movie| %>
				<tr class="text-center">
					<td>#</td>
					<td><%= link_to(movie.title, movie_path(movie)) %></td>
					<td width="60%" class="text-left"><%= movie.description %></td>
					<td><%= movie.theaterdate %></td>
					<td>
						<% if current_user %>
							<%= link_to("Edit", edit_movie_path(movie), class: "btn btn-sm btn-default") %>
							<%= link_to("Delete", movie_path(movie), class: "btn btn-sm btn-default", 
																	method: :delete, 
																	data: { confirm: "Are you sure?" })%>
                        <% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/movies/new.html.erb
<div class="col-md-4 col-md-offset-4">
	<h2>新增电影</h2>
	
	<hr>

	<%= render "form" %>

</div>

app/views/movies/show.html.erb
<div class="col-md-12">
	<div class="group">
		<% if current_user %>
			<span class="pull-right">
				<% if current_user && current_user.is_follower_of?(@movie) %>
					<%= link_to("停止关注", unfollow_movie_path(@movie), method: :post, class: "btn btn-default") %>
					<label class="label label-success"> 已收藏 </label>
				<% else %>
					<%= link_to("收藏电影", follow_movie_path(@movie), method: :post, class: "btn btn-default") %>
					<label class="label label-warning"> 未收藏 </label>
				<% end %>
			</span>
		
			<%= link_to("写评论", new_movie_review_path(@movie), class: "btn btn-default pull-right")%>
		
		
			<%= link_to("编辑电影信息", edit_movie_path(@movie), class: "btn btn-primary pull-right")%>
		<% end %>
	</div>
	<h2><%= @movie.title %></h2>
	<p><%= @movie.theaterdate %></p>
	<p><%= @movie.description %></p>
	
	<table class="table">
		<thead>
			<tr>
				<th>评论内容</th>
				<th>评论人</th>
				<th>评论时间</th>
			</tr>
		</thead>
		<tbody>
			<% @reviews.each do |review| %>
				<tr>
					<td><%= review.content %></td>
					<td><%= review.user.email %></td>
					<td><%= review.created_at %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	
	<div class="text-center">
		<%= will_paginate @reviews %>
	</div>
	
</div>

app/views/reviews/new.html.erb
<h2 class="text-center">新增评论</h2>

<div class="col-md-4 col-md-offset-4">
	<%= simple_form_for [@movie,@review] do |f| %>
		<div class="form-group">
			<%= f.input :content, input_html: { class: "form-control" } %>
		</div>
		<div class="form-actions">
			<%= f.submit "提交", disable_with: "Submiting...", class: "btn btn-primary"%>
		</div>
	<% end %>
</div>

app/views/welcome/index.html.erb
<h1> Hello World! </h1>